version: "3"
services:
  app: &base
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "medwing_test-1"
    tty: true
    stdin_open: true
    volumes:
      - .:/home/medwing
    networks:
      - medwing_test
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis
    environment:
      - RAILS_ENV=development
  postgres:
    image: camptocamp/postgres:9.6
    container_name: "medwing_test_postgres_1"
    networks:
      - medwing_test
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: "medwing_test_redis_1"
    networks:
      - medwing_test
    ports:
      - "6379"
volumes:
  medwing_vol:
networks:
  medwing_test:
