defaults: &defaults
  sidekiq:
    redis_uri: "redis://redis:6379/1"

development:
  <<: *defaults
  secret_key_base: "hey, it's development secrets"
  database:
    pool: 5
    database: 'medwing_dev'
    host: postgres
    port: 5432
    username: 'medwing'
    password: '123456'

test:
  <<: *defaults
  secret_key_base: "hey, it's test secrets"
  database:
    pool: 5
    database: 'medwing_test'
    host: postgres
    port: 5432
    username: 'medwing'
    password: '123456'
